### PR TITLE
Zoom-to-fit polish

### PR DESCRIPTION
**Pull request by alexjball**
https://trello.com/c/bGbc72Eg
https://trello.com/c/aMzuyLQX
https://trello.com/c/A9Br9b2e

- Center the zoomed portion in the visible area of the map, accounting for the floating list UI
- Add a button to the provider list dropdown to zoom to fit, and add tooltips to that and the sort button
- Automatically zoom to fit only when there are new highlighted providers that are not currently in view. So de-selecting a provider never zooms, and selecting a provider only zooms if that provider is not already in view. The in-view check is approximate (it doesn't account for the floating UI or if the map is rotated).

ezgif com-video-to-gif (1)

### CODE REVIEW

**Comment by mikeyavorsky** [comment]
tested in Chrome, behavior appears to match design

**Comment by grinyahoo** [comment]
@alexjball 
.flatMap() fails in safari
flatMap

**Comment by alexjball** [comment]
Good catch! I'll send out a PR to fix.

**Comment by alexjball** [comment]
@grinyahoo It looks like flatmap should work in Safari 12+. Which version are you on? Can you confirm that [1, 2, 3].flatMap(function(x) { return [x] }) fails with the same error?

**Comment by grinyahoo** [comment]
@alexjball [1, 2, 3].flatMap(function(x) { return [x] }) fails as well.
My safari version is 11.1.2

**Pull request merged**
