### PR TITLE
sidebar CSS/HTML refactor: fix scroll to highlighted provider

### PR DESCRIPTION
**Pull request by bhinebaugh**
closes Trello card ["Anibel can see the title of the associated icon card"](https://trello.com/c/H0k3kKrr)

### CODE REVIEW

**Comment by p-somers** [comment]
Screen Shot 2019-08-20 at 7 16 01 PM
It doesn't seem to scroll right to the top of the card for me. Tried on FF and Chrome on OS X

**Comment by bhinebaugh** [comment]
I fixed the bug with sidebar being full height and interfering with map draggability when no providers are displayed.

@p-somers I added a delay before scroll is triggered that's supposed to prevent that behavior... though it should have been in the commits from last week that you tried. Let's check it again with fresh fetch of my branch (I force pushed so history will be messed up)

**Comment by grinyahoo** [comment]
fix
This tweak fixed Chrome not scrolling issue for me.

**Comment by grinyahoo** [comment]
safari_fix
This one fixed map not showing on Safari.

**Comment by alexjball** [comment]
Tested works on Chrome. LGTM

**Comment by alexjball** [comment]
Tested again on chrome, Works! Interestingly this is what it looks like on page load:
Screenshot from 2019-09-10 19-17-58

and this is what it looks like after selecting and deselecting povider types:
Screenshot from 2019-09-10 19-18-15

I'm fine with this behavior!

**Comment by bhinebaugh** [comment]
@alexjball  I'm also fine with that behavior.

Er, I mean, what behavior? I don't see anything. There is nothing to see here. Move along.

**Comment by grinyahoo** [comment]
LGTM, please merge.

@bhinebaugh 
6NdzIG0 - Imgur

**Pull request merged**
