### PR TITLE
Made tabs wide as panel

### PR DESCRIPTION
**Pull request by grinyahoo**
Made tabs wide as the panel, also centered tabs heading

### CODE REVIEW

**Comment by alexjball** [comment]
LGTM except this spacing issue.
Screenshot from 2019-11-01 14-54-43

**Comment by grinyahoo** [comment]
@alexjball it's the same bug from the previous PR. 
Do you think it's better to close this PR, rebase and roll another one?

**Comment by alexjball** [comment]
@grinyahoo I don't see this issue at the tip of reboot, so I do think it's from changes in this PR. I would suggest merging in reboot and then comparing between reboot and this branch

git checkout reboot
git pull upstream reboot
git checkout tabs-wide-as-panel
git merge reboot

then compare

git checkout reboot
npm start

to

git checkout tabs-wide-as-panel
npm start

**Comment by alexjball** [comment]
LGTM!

**Pull request merged**
