### PR TITLE
Providers to print/email ordered as they are in saved list

### PR DESCRIPTION
**Pull request by grinyahoo**
Refers to card:
Users can reorder providers in the saved list.
Removed category header.

### CODE REVIEW

**Comment by grinyahoo** [comment]
PR 209 must be merged prior to this one.

**Comment by alexjball** [comment]
@grinyahoo Did you mean to close this? I was about to merge it!

**Comment by grinyahoo** [comment]
@alexjball Oh, sorry. I was going to rebase and open another PR. I can reopen this one if you made progress.

**Comment by alexjball** [comment]
Looks great! Just had to resolve some fiddly merge conflicts.

**Pull request merged**
