### PR TITLE
Map style load bug fix

### PR DESCRIPTION
**Pull request by p-somers**

### CODE REVIEW

**Comment by alexjball** [comment]
Another way to do this is to use React state with a `loaded: boolean` field. It is initially false and at the end of the load callback you call `setState({loaded: true})`. This causes React to re-render the component and call `componentDidUpdate`, which would return early if the map isn't loaded. 

The benefit to this is that the update logic is still synchronous so may be easier to understand. Using state also provides a source of truth for the map's loading status: only manipulate the map if `this.state.loaded` is true.

Does this bug repro if you let the map finish loading before using it? I could only repro by adjusting the distance filter right after refreshing

**Comment by p-somers** [comment]
Ah... yeah that's a much better way. Hold on

**Review by MattRC7 — COMMENTED** [review]
Code looks good. Testing before approval

**Review by MattRC7 — APPROVED** [review]
Tests passed, okay to merge @sashamaryl

**Pull request merged**
